### ISSUE TITLE
Portable Crafting Module has no texture

### ISSUE THREAD

**Issue by HyperMan19680** [QMXTech/MachineMusePowersuits#16] opened 2015-01-06 05:18 UTC
https://www.dropbox.com/s/metleovql3ftoo7/Screenshot%202015-01-05%2023.14.09.png?dl=0

That should be enough. Also, the tool section with the Shrinking Module also cannot be accessed. It instead points to the modifiers.

**Comment by Korynkai** [comment] 2015-01-06 16:18
Huh, another issue that I noticed in testing but forgot to make a note of. Thanks, I'll get right on this.

As for the tool section with the Shrinking Module... There is an odd bug (which I'm currently working on and haven't really come up with a solution yet) that skews the mouse cursor coordinates in the MuseUI screen(s)... Have you tried clicking right below the Shrinking Module? Though the section with the diamond drill addon also was inaccessible because of this bug... But as such, the second section of this report seems to be a duplicate of #12

**Comment by Korynkai** [comment] 2015-01-06 18:50
Crafting module fixed in internal build. I had changed the modid to be inserted through gradle's Minecraft block and removed the "modid" variable. Seems more than I thought was dependant on that variable, which is now also set by gradle.

**Comment by Korynkai** [comment] 2015-02-14 07:18
Fixed in this release.

**Closed by Korynkai** 2015-02-14 07:18 UTC
Labels: Bug, Code Finished (GitLab Unstable), Recently Introduced
